### ISSUE TITLE
Gems update failed

### ISSUE THREAD

**Issue by brenorb** [TolgaTatli/Moonrise#3]
The template website is no longer online due to failure of a gem update.

**Comment by TolgaTatli** [comment]
Can you try the installation guide here and update the gems again?

https://jekyllrb.com/docs/ruby-101/#gems

**Comment by TolgaTatli** [comment]
It was giving gems update problems due to a problem with Docker.

Since the version is not up to date, I just reviewed the theme again and it is working smoothly. 
I ask you to try again. I will check in case there is a problem.

Enjoy the Moonrise :))
